# Generated by Django 4.0.4 on 2022-05-25 00:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(verbose_name='serial number')),
                ('list_year', models.IntegerField(verbose_name='year of sale')),
                ('date_recorded', models.DateTimeField(verbose_name='timestamp of sale')),
                ('town', models.CharField(max_length=100, verbose_name='town of the property')),
                ('address', models.CharField(max_length=250, verbose_name='address of the property')),
                ('assessed_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='estimated value')),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='sales amount')),
                ('sales_ratio', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='ratio of sales amount and estimated value')),
                ('property_type', models.CharField(choices=[('Single Family', 'Single Family'), ('Condo', 'Condo')], max_length=50, verbose_name='type of property')),
                ('residential_type', models.CharField(choices=[('Single Family', 'Single Family'), ('Condo', 'Condo')], max_length=50, verbose_name='genre of residence')),
                ('non_use_code', models.CharField(max_length=50, verbose_name='use state code')),
                ('assessor_remarks', models.CharField(max_length=1000, verbose_name='professional remarks')),
                ('opm_remarks', models.CharField(max_length=1000, verbose_name='official comment')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='geographic coordinate')),
            ],
        ),
    ]
