# Generated by Django 4.0.4 on 2022-05-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='assessed_value',
            field=models.CharField(max_length=20, verbose_name='estimated value'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='list_year',
            field=models.CharField(max_length=10, verbose_name='year of sale'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_amount',
            field=models.CharField(max_length=20, verbose_name='sales amount'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_ratio',
            field=models.CharField(max_length=20, verbose_name='ratio of sales amount and estimated value'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='serial_number',
            field=models.CharField(max_length=20, verbose_name='serial number'),
        ),
    ]
