# Generated by Django 4.0.4 on 2022-05-28 20:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_sales', '0002_alter_salesrecord_assessed_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address of the property'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='assessed_value',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='estimated value'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='assessor_remarks',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='professional remarks'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='date_recorded',
            field=models.DateTimeField(blank=True, null=True, verbose_name='timestamp of sale'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='list_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='year of sale'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='geographic coordinate'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='non_use_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='use state code'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='opm_remarks',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='official comment'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Single Family', 'Single Family'), ('Condo', 'Condo')], max_length=50, null=True, verbose_name='type of property'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='residential_type',
            field=models.CharField(blank=True, choices=[('Single Family', 'Single Family'), ('Condo', 'Condo')], max_length=50, null=True, verbose_name='genre of residence'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_amount',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='sales amount'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_ratio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ratio of sales amount and estimated value'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='serial number'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='town of the property'),
        ),
    ]
