# Generated by Django 4.0.4 on 2022-05-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_sales', '0003_alter_salesrecord_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='sales_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sales identifier'),
        ),
    ]
