from django.utils.translation import gettext_lazy as _
from django.db import models


class Property(models.Model):
    property_number = models.DecimalField(_('Property Number'), max_digits=15, decimal_places=0, blank=True, null=True)
    county_number = models.DecimalField(_('County Number'), max_digits=10, decimal_places=0, blank=True, null=True)
    county_name = models.CharField(_('County Name'), max_length=100, blank=True, null=True)
    city_number = models.DecimalField(_('City Name'), max_digits=10, decimal_places=0, blank=True, null=True)
    city_name = models.CharField(_('City Name'), max_length=100, blank=True, null=True)
    gnr = models.DecimalField(_('Cadastral Unit Number'), max_digits=10, decimal_places=0, blank=True, null=True)
    bnr = models.DecimalField(_('Property Unit Number'), max_digits=10, decimal_places=0, blank=True, null=True)
    fnr = models.DecimalField(_('Lease Number'), max_digits=10, decimal_places=0, blank=True, null=True)
    snr = models.DecimalField(_('Unit Number'), max_digits=10, decimal_places=0, blank=True, null=True)
    bruksnavn = models.CharField(_('Subfarm Name'), max_length=100, blank=True, null=True)
    antall_teiger = models.DecimalField(_('Number of plots'), max_digits=10, decimal_places=0, blank=True, null=True)
    areal = models.DecimalField(_('Property Area'), max_digits=15, decimal_places=4, blank=True, null=True)
    arealkilde_nr = models.DecimalField(_('Source Number'), max_digits=10, decimal_places=0, blank=True, null=True)
    arealkilde_navn = models.CharField(_('Source Name'), max_length=100, blank=True, null=True)
    nærings_kode = models.CharField(_('Industry Code'), max_length=100, blank=True, null=True)
    nærings_kode_navn = models.CharField(_('Industry Code Name'), max_length=100, blank=True, null=True)
    tinglyst = models.BooleanField(_('Written Contract Exists'), blank=True, null=True)
    omsetningsdato = models.DecimalField(_('Turnover Date'), max_digits=10, decimal_places=0, blank=True, null=True)
    kjopesum = models.DecimalField(_('Purchase Price'), max_digits=20, decimal_places=2, blank=True, null=True)
    omsetningstype_kode = models.CharField(_('Turnover Type Code'), max_length=100, blank=True, null=True)
    omsetningstype_navn = models.CharField(_('Turnover Type Name'), max_length=200, blank=True, null=True)
    sameie_teller = models.DecimalField(_('Number of co-ownership'), max_digits=10, decimal_places=0, blank=True, null=True)
    sameie_nevner = models.DecimalField(_('Maximum allowed co-ownership'), max_digits=10, decimal_places=0, blank=True, null=True)
    etablert_dato = models.DecimalField(_('Date of Establishment'), max_digits=10, decimal_places=0, blank=True, null=True)
    etablert_aar = models.DecimalField(_('Year of Establishment'), max_digits=10, decimal_places=0, blank=True, null=True)
    eiendomstype_kode = models.DecimalField(_('Property Type Code'), max_digits=10, decimal_places=0, blank=True, null=True)
    eiendomstype_navn = models.CharField(_('Property Type'), max_length=30, blank=True, null=True)
    bygning_paa_eiendom = models.CharField(_('Building on Property'), max_length=100, blank=True, null=True)
    bygning_paa_eiendom_navn = models.CharField(_('Building on Property Name'), max_length=200, blank=True, null=True)
    antall_bygninger = models.DecimalField(_('Number of Buildings'), max_digits=10, decimal_places=0, blank=True, null=True)
    antall_adresser = models.DecimalField(_('Number of Addresses'), max_digits=10, decimal_places=0, blank=True, null=True)
    lkoord_sys_nr = models.DecimalField(_('Coordinate System Number'), max_digits=10, decimal_places=0, blank=True, null=True)
    lkoord_sys_navn = models.CharField(_('Coordinate System Name'), max_length=25, blank=True, null=True)
    lkooelokx = models.DecimalField(_('UTM X coordinate'), max_digits=30, decimal_places=10, blank=True, null=True)
    lkooeloky = models.DecimalField(_('UTM Y coordinate'), max_digits=30, decimal_places=10, blank=True, null=True)
    
    def __str__(self):
        return self.bruksnavn


class PropertyAddress(models.Model):
    property_number = models.IntegerField(_('Property Number'), blank=True, null=True)
    city_number = models.IntegerField(_('City Name'), blank=True, null=True)
    city_name = models.CharField(_('City Name'), max_length=100, blank=True, null=True)
    gnr = models.IntegerField(_('Cadastral Unit Number'), blank=True, null=True)
    bnr = models.IntegerField(_('Property Unit Number'), blank=True, null=True)
    fnr = models.IntegerField(_('Lease Number'), blank=True, null=True)
    snr = models.IntegerField(_('Unit Number'), blank=True, null=True)
    eiendomstype_kode = models.IntegerField(_('Property Type Code'), blank=True, null=True)
    eiendomstype_navn = models.CharField(_('Property Type'), max_length=30, blank=True, null=True)
    areal = models.DecimalField(_('Property Area'), max_digits=15, decimal_places=4, blank=True, null=True)
    bruksnavn = models.CharField(_('Subfarm Name'), max_length=100, blank=True, null=True)
    adresse_id = models.IntegerField(_('Address ID'), blank=True, null=True)
    gatenavn = models.CharField(_('Gate Name'), max_length=200, blank=True, null=True)
    gatenavnkode = models.IntegerField(_('Gate Number'), blank=True, null=True)
    husnummer = models.IntegerField(_('Number of Houses'), blank=True, null=True)
    bokstav = models.CharField(_('Letter'), max_length=5, blank=True, null=True)
    undernummer = models.IntegerField(_('Number of Subunits'), blank=True, null=True)
    post_nr = models.IntegerField(_('Postal Code'), blank=True, null=True)
    poststed = models.CharField(_('Postal Location'), max_length=100, blank=True, null=True)
    
    def __str__(self):
        return self.bruksnavn


class Building(models.Model):
    building_id = models.DecimalField(_('Building ID'), max_digits=15, decimal_places=0, blank=True, null=True)
    county_number = models.DecimalField(_('County Number'), max_digits=10, decimal_places=0, blank=True, null=True)
    county_name = models.CharField(_('County Name'), max_length=50, blank=True, null=True)
    city_number = models.DecimalField(_('City Name'), max_digits=10, decimal_places=0, blank=True, null=True)
    city_name = models.CharField(_('City Name'), max_length=100, blank=True, null=True)
    building_number = models.DecimalField(_('Building Number'), max_digits=10, decimal_places=0, blank=True, null=True)
    bygning_lnr = models.DecimalField(_('Building LNR'), max_digits=10, decimal_places=0, blank=True, null=True)
    bygningstype_nr = models.DecimalField(_('Building Type Number'), max_digits=10, decimal_places=0, blank=True, null=True)
    bygningstype_navn = models.CharField(_('Building Type Name'), max_length=100, blank=True, null=True)
    bygningsstatus_nr = models.CharField(_('Building Status Number'), max_length=10, blank=True, null=True)
    bygningsstatus_navn = models.CharField(_('Building Status Name'), max_length=100, blank=True, null=True)
    godkjent_dato = models.DecimalField(_('Approved Date'), max_digits=10, decimal_places=0, blank=True, null=True)
    igangsatt_dato = models.DecimalField(_('Start Date'), max_digits=10, decimal_places=0, blank=True, null=True)
    tatt_i_bruk_dato = models.DecimalField(_('In Use Date'), max_digits=10, decimal_places=0, blank=True, null=True)
    naeringsgruppe_kode = models.CharField(_('Industry Group Code'), max_length=5, blank=True, null=True)
    naeringsgruppe_navn = models.CharField(_('Industry Group Name'), max_length=100, blank=True, null=True)
    paabygg_tilbygg_kode = models.CharField(_('Annex Code'), max_length=5, blank=True, null=True)
    paabygg_tilbygg_navn = models.CharField(_('Annex Name'), max_length=20, blank=True, null=True)
    vannforsyning_nr = models.DecimalField(_('Water Supply Number'), max_digits=10, decimal_places=0, blank=True, null=True)
    vannforsyning_navn = models.CharField(_('Water Supply Name'), max_length=50, blank=True, null=True)
    bruksareal_totalt = models.DecimalField(_('UFS Total'), max_digits=15, decimal_places=4, blank=True, null=True)
    bruksareal_bolig = models.DecimalField(_('UFS Home'), max_digits=15, decimal_places=4, blank=True, null=True)
    bruksareal_annet_bolig = models.DecimalField(_('UFS Other'), max_digits=15, decimal_places=4, blank=True, null=True)
    antall_etasjer = models.DecimalField(_('Number of Floors'), max_digits=10, decimal_places=0, blank=True, null=True)
    antall_boliger = models.DecimalField(_('Number of Apartments'), max_digits=10, decimal_places=0, blank=True, null=True)
    lkoordinatsystem_nr = models.DecimalField(_('Coordinate System Number'), max_digits=10, decimal_places=0, blank=True, null=True)
    lkoordinatsystem_navn = models.CharField(_('Coordinate System Name'), max_length=50, blank=True, null=True)
    lkoordinat_kvalitet_kode = models.CharField(_('Coordinate Quality Number'), max_length=10, blank=True, null=True)
    lkoordinat_kvalitet_navn = models.CharField(_('Coordinate Quality Name'), max_length=50, blank=True, null=True)
    lx_koordinat = models.DecimalField(_('UTM X coordinate'), max_digits=30, decimal_places=10, blank=True, null=True)
    ly_koordinat = models.DecimalField(_('UTM Y coordinate'), max_digits=30, decimal_places=10, blank=True, null=True)
    lz_koordinat = models.DecimalField(_('UTM Z coordinate'), max_digits=30, decimal_places=10, blank=True, null=True)
    eiendom_antall = models.DecimalField(_('Number of Properties'), max_digits=10, decimal_places=0, blank=True, null=True)
    har_heis = models.BooleanField(_('Has a Lift'), blank=True, null=True)
    bebygd_areal = models.DecimalField(_('Built Area'), max_digits=15, decimal_places=4, blank=True, null=True)
    
    def __str__(self):
        return self.building_number
