from django.utils.translation import gettext_lazy as _
from django.db import models


class SmallBusiness(models.Model):
    account_number = models.CharField(_('Account Number'), max_length=50, blank=True, null=True)
    annual_report_due_date = models.DateTimeField(_('Annual Report Due Date'), blank=True, null=True)
    began_transacting_in_ct = models.DateTimeField(_('Connecticut Transaction Start Date'), blank=True, null=True)
    business_city = models.CharField(_('City of Business'), max_length=200, blank=True, null=True)
    business_country = models.CharField(_('Country of Business'), max_length=200, blank=True, null=True)
    business_email_address = models.EmailField(_('Business Email'), blank=True, null=True)
    business_name_in_state_country = models.CharField(_('Local Business Name'), max_length=250, blank=True, null=True)
    business_state = models.CharField(_('State of Business'), max_length=50, blank=True, null=True)
    business_street = models.CharField(_('Street Name of Business'), max_length=200, blank=True, null=True)
    business_type = models.CharField(_('Type of Business'), max_length=200, blank=True, null=True)
    business_unit = models.CharField(_('Business unit'), max_length=50, blank=True, null=True)
    business_zip_code = models.CharField(_('Zipcode of Business'), max_length=10, blank=True, null=True)
    category_survey_email_address = models.EmailField(_('Category Survey Email'), blank=True, null=True)
    citizenship = models.CharField(_('Owner Citizenship'), max_length=200, blank=True, null=True)
    country_formation = models.CharField(_('Country of Origin'), max_length=200, blank=True, null=True)
    created_on = models.DateTimeField(_('Establish Date'), blank=True, null=True)
    date_of_organization_meeting = models.DateTimeField(_('Organization Meeting Date'), blank=True, null=True)
    disable_person_owned_organization = models.BooleanField(_('Is owner disabled?'), blank=True, null=True)
    dissolution_date = models.DateTimeField(_('Date of Dissolution'), blank=True, null=True)
    formation_place = models.CharField(_('Place of Formation'), max_length=200, blank=True, null=True)
    business_identifier = models.CharField(_('Business ID'), max_length=50, blank=True, null=True)
    mail_jurisdiction = models.CharField(_('Mailing Jurisdiction'), max_length=200, blank=True, null=True)
    mailing_address = models.CharField(_('Mailing Address'), max_length=200, blank=True, null=True)
    mailing_international_address = models.CharField(_('Mailing Address International'), max_length=200, blank=True, null=True)
    mailing_jurisdiction_address = models.CharField(_('Mailing Jurisdiction Address'), max_length=200, blank=True, null=True)
    mailing_jurisdiction_business_city = models.CharField(_('Mailing Jurisdiction City of Business'), max_length=200, blank=True, null=True)
    mailing_jurisdiction_business_country = models.CharField(_('Mailing Jurisdiction Country of Business'), max_length=200, blank=True, null=True)
    mailing_jurisdiction_business_state = models.CharField(_('Mailing Jurisdiction State of Business'), max_length=200, blank=True, null=True)
    mailing_jurisdiction_business_street = models.CharField(_('Mailing Jurisdiction Street name of Business'), max_length=200, blank=True, null=True)
    mailing_jurisdiction_business_unit = models.CharField(_('Mailing Jurisdiction Unit of Business'), max_length=50, blank=True, null=True)
    mailing_jurisdiction_business_zip_code = models.CharField(_('Mailing Jurisdiction Zipcode of Business'), max_length=10, blank=True, null=True)
    minority_owned_organization = models.BooleanField(_('Does owner belong to minority groups?'), blank=True, null=True)
    naics_code = models.CharField(_('NAICS code'), max_length=200, blank=True, null=True)
    naics_sub_code = models.CharField(_('NAICS sub code'), max_length=200, blank=True, null=True)
    name = models.CharField(_('Business Name'), max_length=200, blank=True, null=True)
    office_jurisdiction_address = models.CharField(_('Office Jurisdiction Address'), max_length=200, blank=True, null=True)
    office_jurisdiction_business_city = models.CharField(_('City of Office Jurisdiction'), max_length=200, blank=True, null=True)
    office_jurisdiction_business_state = models.CharField(_('State of Office Jurisdiction'), max_length=200, blank=True, null=True)
    office_jurisdiction_business_street = models.CharField(_('Street name of Office Jurisdiction'), max_length=200, blank=True, null=True)
    office_jurisdiction_business_unit = models.CharField(_('Office Jurisdiction Unit of Business'), max_length=50, blank=True, null=True)
    office_jurisdiction_business_zip_code = models.CharField(_('Zipcode of Office Jurisdiction'), max_length=10, blank=True, null=True)
    office_jurisdiction_country = models.CharField(_('Country of Office Jurisdiction'), max_length=200, blank=True, null=True)
    reason_for_administrative_dissolution = models.CharField(_('Reason for Administrative Dissolution'), max_length=500, blank=True, null=True)
    record_address = models.CharField(_('Address of Record'), max_length=200, blank=True, null=True)
    records_address_city = models.CharField(_('City of Record'), max_length=200, blank=True, null=True)
    records_address_country = models.CharField(_('Country of Record'), max_length=200, blank=True, null=True)
    records_address_state = models.CharField(_('State of Record'), max_length=200, blank=True, null=True)
    records_address_street = models.CharField(_('Street name of Record'), max_length=200, blank=True, null=True)
    records_address_unit = models.CharField(_('Unit of Record'), max_length=200, blank=True, null=True)
    records_address_zip_code = models.CharField(_('Zipcode of Record'), max_length=10, blank=True, null=True)
    registration_date = models.DateTimeField(_('Date of Registration'), blank=True, null=True)
    state_or_territory_formation = models.CharField(_('State of Formation'), max_length=200, blank=True, null=True)
    status = models.CharField(_('Process status'), max_length=50, blank=True, null=True)
    sub_status = models.CharField(_('Process sub-status'), max_length=200, blank=True, null=True)
    total_authorized_shares = models.IntegerField(_('Number of Authorized Shares'), blank=True, null=True)
    veteran_owned_organization = models.BooleanField(_('Is owner veteran?'), blank=True, null=True)
    woman_owned_organization = models.BooleanField(_('Is owner woman'), blank=True, null=True)
    
    def __str__(self):
        return self.name
