# Generated by Django 4.0.4 on 2022-06-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmallBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number')),
                ('annual_report_due_date', models.DateTimeField(blank=True, null=True, verbose_name='Annual Report Due Date')),
                ('began_transacting_in_ct', models.DateTimeField(blank=True, null=True, verbose_name='Connecticut Transaction Start Date')),
                ('business_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City of Business')),
                ('business_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country of Business')),
                ('business_email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Business Email')),
                ('business_name_in_state_country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Local Business Name')),
                ('business_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State of Business')),
                ('business_street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Street Name of Business')),
                ('business_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Type of Business')),
                ('business_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Business unit')),
                ('business_zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zipcode of Business')),
                ('category_survey_email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Category Survey Email')),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner Citizenship')),
                ('country_formation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country of Origin')),
                ('created_on', models.DateTimeField(blank=True, null=True, verbose_name='Establish Date')),
                ('date_of_organization_meeting', models.DateTimeField(blank=True, null=True, verbose_name='Organization Meeting Date')),
                ('disable_person_owned_organization', models.BooleanField(blank=True, null=True, verbose_name='Is owner disabled?')),
                ('dissolution_date', models.DateTimeField(blank=True, null=True, verbose_name='Date of Dissolution')),
                ('formation_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Formation')),
                ('business_identifier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Business ID')),
                ('mail_jurisdiction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mailing Jurisdiction')),
                ('mailing_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mailing Address')),
                ('mailing_international_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mailing Address International')),
                ('mailing_jurisdiction_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mailing Jurisdiction Address')),
                ('mailing_jurisdiction_business_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mailing Jurisdiction City of Business')),
                ('mailing_jurisdiction_business_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mailing Jurisdiction Country of Business')),
                ('mailing_jurisdiction_business_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mailing Jurisdiction State of Business')),
                ('mailing_jurisdiction_business_street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mailing Jurisdiction Street name of Business')),
                ('mailing_jurisdiction_business_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mailing Jurisdiction Unit of Business')),
                ('mailing_jurisdiction_business_zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mailing Jurisdiction Zipcode of Business')),
                ('minority_owned_organization', models.BooleanField(blank=True, null=True, verbose_name='Does owner belong to minority groups?')),
                ('naics_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='NAICS code')),
                ('naics_sub_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='NAICS sub code')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Business Name')),
                ('office_jurisdiction_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Office Jurisdiction Address')),
                ('office_jurisdiction_business_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City of Office Jurisdiction')),
                ('office_jurisdiction_business_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State of Office Jurisdiction')),
                ('office_jurisdiction_business_street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Street name of Office Jurisdiction')),
                ('office_jurisdiction_business_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Office Jurisdiction Unit of Business')),
                ('office_jurisdiction_business_zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zipcode of Office Jurisdiction')),
                ('office_jurisdiction_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country of Office Jurisdiction')),
                ('reason_for_administrative_dissolution', models.CharField(blank=True, max_length=500, null=True, verbose_name='Reason for Administrative Dissolution')),
                ('record_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address of Record')),
                ('records_address_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City of Record')),
                ('records_address_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country of Record')),
                ('records_address_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State of Record')),
                ('records_address_street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Street name of Record')),
                ('records_address_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit of Record')),
                ('records_address_zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zipcode of Record')),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name='Date of Registration')),
                ('state_or_territory_formation', models.CharField(blank=True, max_length=100, null=True, verbose_name='State of Formation')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Process status')),
                ('sub_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Process sub-status')),
                ('total_authorized_shares', models.IntegerField(blank=True, null=True, verbose_name='Number of Authorized Shares')),
                ('veteran_owned_organization', models.BooleanField(blank=True, null=True, verbose_name='Is owner veteran?')),
                ('woman_owned_organization', models.BooleanField(blank=True, null=True, verbose_name='Is owner woman')),
            ],
        ),
    ]
