# Generated by Django 4.0.4 on 2022-06-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallbusiness',
            name='business_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City of Business'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='business_country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Country of Business'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='citizenship',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Owner Citizenship'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='country_formation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Country of Origin'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='formation_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Place of Formation'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='mail_jurisdiction',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mailing Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='mailing_jurisdiction_business_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mailing Jurisdiction City of Business'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='mailing_jurisdiction_business_country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mailing Jurisdiction Country of Business'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='mailing_jurisdiction_business_state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mailing Jurisdiction State of Business'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='naics_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NAICS code'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='naics_sub_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NAICS sub code'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='office_jurisdiction_business_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City of Office Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='office_jurisdiction_business_state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='State of Office Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='office_jurisdiction_country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Country of Office Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='records_address_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City of Record'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='records_address_country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Country of Record'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='records_address_state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='State of Record'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='records_address_unit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unit of Record'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='state_or_territory_formation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='State of Formation'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='sub_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Process sub-status'),
        ),
    ]
