# Generated by Django 4.0.4 on 2022-06-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_smallbusiness_business_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallbusiness',
            name='total_authorized_shares',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='Number of Authorized Shares'),
        ),
    ]
