# Generated by Django 4.0.4 on 2022-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_smallbusiness_total_authorized_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallbusiness',
            name='business_zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zipcode of Business'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='mailing_jurisdiction_business_zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mailing Jurisdiction Zipcode of Business'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='office_jurisdiction_business_zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zipcode of Office Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='smallbusiness',
            name='records_address_zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zipcode of Record'),
        ),
    ]
