# Generated by Django 4.0.4 on 2022-07-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_number', models.IntegerField(blank=True, null=True, verbose_name='Property Number')),
                ('county_number', models.IntegerField(blank=True, null=True, verbose_name='County Number')),
                ('county_name', models.IntegerField(blank=True, null=True, verbose_name='County Name')),
                ('city_number', models.IntegerField(blank=True, null=True, verbose_name='City Name')),
                ('gnr', models.IntegerField(blank=True, null=True, verbose_name='Cadastral Unit Number')),
                ('bnr', models.IntegerField(blank=True, null=True, verbose_name='Property Unit Number')),
                ('fnr', models.IntegerField(blank=True, null=True, verbose_name='Lease Number')),
                ('snr', models.IntegerField(blank=True, null=True, verbose_name='Unit Number')),
                ('bruksnavn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subfarm Name')),
                ('antall_teiger', models.IntegerField(blank=True, null=True, verbose_name='Number of plots')),
                ('area', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Property Area')),
                ('arealkilde_nr', models.IntegerField(blank=True, null=True, verbose_name='Source Number')),
                ('arealkilde_navn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Source Name')),
                ('natrings_kode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry Code')),
                ('natrings_kode_navn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry Code Name')),
                ('tinglyst', models.BooleanField(blank=True, null=True, verbose_name='Written Contract Exists')),
                ('omsetnings_dato', models.IntegerField(blank=True, null=True, verbose_name='Turnover Date')),
                ('kjopesum', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Purchase Price')),
                ('omsetningstype_kode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turnover Type Code')),
                ('omsetningstype_navn', models.CharField(blank=True, max_length=200, null=True, verbose_name='Turnover Type Name')),
                ('sameie_teller', models.IntegerField(blank=True, null=True, verbose_name='Number of co-ownership')),
                ('sameie_nevner', models.IntegerField(blank=True, null=True, verbose_name='Maximum allowed co-ownership')),
                ('etablert_dato', models.IntegerField(blank=True, null=True, verbose_name='Date of Establishment')),
                ('etablert_aar', models.IntegerField(blank=True, null=True, verbose_name='Year of Establishment')),
                ('eiendomstype_kode', models.IntegerField(blank=True, null=True, verbose_name='Property Type Code')),
                ('eiendomstype_navn', models.CharField(blank=True, max_length=30, null=True, verbose_name='Property Type')),
                ('bygning_paa_eiendom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Building on Property')),
                ('bygning_paa_eiendom_navn', models.CharField(blank=True, max_length=200, null=True, verbose_name='Building on Property Name')),
                ('antall_bygninger', models.IntegerField(blank=True, null=True, verbose_name='Number of Buildings')),
                ('antall_addresser', models.IntegerField(blank=True, null=True, verbose_name='Number of Addresses')),
                ('lkoord_sys_nr', models.IntegerField(blank=True, null=True, verbose_name='Coordinate System Number')),
                ('lkoord_sys_navn', models.CharField(blank=True, max_length=25, null=True, verbose_name='Coordinate System Name')),
                ('lkooelokx', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='UTM X coordinate')),
                ('lkooeloky', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='UTM Y coordinate')),
            ],
        ),
    ]
