# Generated by Django 4.0.4 on 2022-07-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField(blank=True, null=True, verbose_name='Building ID')),
                ('county_number', models.IntegerField(blank=True, null=True, verbose_name='County Number')),
                ('county_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='County Name')),
                ('city_number', models.IntegerField(blank=True, null=True, verbose_name='City Name')),
                ('city_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='City Name')),
                ('building_number', models.IntegerField(blank=True, null=True, verbose_name='Building Number')),
                ('bygning_lnr', models.IntegerField(blank=True, null=True, verbose_name='Building LNR')),
                ('bygningstype_nr', models.IntegerField(blank=True, null=True, verbose_name='Building Type Number')),
                ('bygningstype_navn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Building Type Name')),
                ('bygningsstatus_nr', models.IntegerField(blank=True, null=True, verbose_name='Building Status Number')),
                ('bygningsstatus_navn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Building Status Name')),
                ('godkjent_dato', models.IntegerField(blank=True, null=True, verbose_name='Approved Date')),
                ('igangsatt_dato', models.IntegerField(blank=True, null=True, verbose_name='Start Date')),
                ('tatt_i_bruk_dato', models.IntegerField(blank=True, null=True, verbose_name='In Use Date')),
                ('naeringsgruppe_kode', models.CharField(blank=True, max_length=5, null=True, verbose_name='Industry Group Code')),
                ('naeringsgruppe_navn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry Group Name')),
                ('paabygg_tilbygg_kode', models.CharField(blank=True, max_length=5, null=True, verbose_name='Annex Code')),
                ('paabygg_tilbygg_navn', models.CharField(blank=True, max_length=20, null=True, verbose_name='Annex Name')),
                ('vannforsyning_nr', models.IntegerField(blank=True, null=True, verbose_name='Water Supply Number')),
                ('vannforsyning_navn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Water Supply Name')),
                ('bruksareal_totalt', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='UFS Total')),
                ('bruksareal_bolig', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='UFS Home')),
                ('bruksareal_annet_bolig', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='UFS Other')),
                ('antall_etasjer', models.IntegerField(blank=True, null=True, verbose_name='Number of Floors')),
                ('antall_boliger', models.IntegerField(blank=True, null=True, verbose_name='Number of Apartments')),
                ('lkoordinatsystem_nr', models.IntegerField(blank=True, null=True, verbose_name='Coordinate System Number')),
                ('lkoordinatsystem_navn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coordinate System Name')),
                ('lkoordinat_kvalitet_nr', models.IntegerField(blank=True, null=True, verbose_name='Coordinate Quality Number')),
                ('lkoordinat_kvalitet_navn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coordinate Quality Name')),
                ('lx_koordinat', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='UTM X coordinate')),
                ('ly_koordinat', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='UTM Y coordinate')),
                ('lz_koordinat', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='UTM Z coordinate')),
                ('eiendom_antall', models.IntegerField(blank=True, null=True, verbose_name='Number of Properties')),
                ('har_heis', models.BooleanField(blank=True, null=True, verbose_name='Has a Lift')),
                ('bebygd_areal', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Built Area')),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Property Area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='county_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='County Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='kjopesum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Purchase Price'),
        ),
    ]
