# Generated by Django 4.0.4 on 2022-07-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_building_alter_property_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City Name'),
        ),
    ]
