# Generated by Django 4.0.4 on 2022-07-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_property_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_number', models.IntegerField(blank=True, null=True, verbose_name='Property Number')),
                ('city_number', models.IntegerField(blank=True, null=True, verbose_name='City Name')),
                ('city_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='City Name')),
                ('gnr', models.IntegerField(blank=True, null=True, verbose_name='Cadastral Unit Number')),
                ('bnr', models.IntegerField(blank=True, null=True, verbose_name='Property Unit Number')),
                ('fnr', models.IntegerField(blank=True, null=True, verbose_name='Lease Number')),
                ('snr', models.IntegerField(blank=True, null=True, verbose_name='Unit Number')),
                ('eiendomstype_kode', models.IntegerField(blank=True, null=True, verbose_name='Property Type Code')),
                ('eiendomstype_navn', models.CharField(blank=True, max_length=30, null=True, verbose_name='Property Type')),
                ('areal', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Property Area')),
                ('bruksnavn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subfarm Name')),
                ('adresse_id', models.IntegerField(blank=True, null=True, verbose_name='Address ID')),
                ('gatenavn', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gate Name')),
                ('gatenavnkode', models.IntegerField(blank=True, null=True, verbose_name='Gate Number')),
                ('husnummer', models.IntegerField(blank=True, null=True, verbose_name='Number of Houses')),
                ('bokstav', models.CharField(blank=True, max_length=5, null=True, verbose_name='Letter')),
                ('undernummer', models.IntegerField(blank=True, null=True, verbose_name='Number of Subunits')),
                ('post_nr', models.IntegerField(blank=True, null=True, verbose_name='Postal Code')),
                ('poststed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Postal Location')),
            ],
        ),
    ]
