# Generated by Django 4.0.4 on 2022-08-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_propertyaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area',
            new_name='areal',
        ),
    ]
