# Generated by Django 4.0.4 on 2022-08-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_rename_area_property_areal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='natrings_kode',
            new_name='nærings_kode',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='natrings_kode_navn',
            new_name='nærings_kode_navn',
        ),
    ]
