# Generated by Django 4.0.4 on 2022-08-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_rename_natrings_kode_property_nærings_kode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='omsetnings_dato',
            new_name='omsetningsdato',
        ),
    ]
