# Generated by Django 4.0.4 on 2022-08-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_rename_omsetnings_dato_property_omsetningsdato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='antall_addresser',
            new_name='antall_adresser',
        ),
    ]
