# Generated by Django 4.0.4 on 2022-08-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_rename_antall_addresser_property_antall_adresser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='arealkilde_navn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bygning_paa_eiendom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Building on Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='county_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='County Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='nærings_kode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry Code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='nærings_kode_navn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry Code Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='omsetningstype_kode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Turnover Type Code'),
        ),
    ]
