# Generated by Django 4.0.4 on 2022-08-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_alter_property_arealkilde_navn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='antall_adresser',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Number of Addresses'),
        ),
        migrations.AlterField(
            model_name='property',
            name='antall_bygninger',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Number of Buildings'),
        ),
        migrations.AlterField(
            model_name='property',
            name='antall_teiger',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Number of plots'),
        ),
        migrations.AlterField(
            model_name='property',
            name='arealkilde_nr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Source Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bnr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Property Unit Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='county_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='County Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='eiendomstype_kode',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Property Type Code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='etablert_aar',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Year of Establishment'),
        ),
        migrations.AlterField(
            model_name='property',
            name='etablert_dato',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Date of Establishment'),
        ),
        migrations.AlterField(
            model_name='property',
            name='fnr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Lease Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gnr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Cadastral Unit Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='lkoord_sys_nr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Coordinate System Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='omsetningsdato',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Turnover Date'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Property Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sameie_nevner',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Maximum allowed co-ownership'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sameie_teller',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Number of co-ownership'),
        ),
        migrations.AlterField(
            model_name='property',
            name='snr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Unit Number'),
        ),
    ]
