# Generated by Django 4.0.4 on 2022-08-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_alter_property_antall_adresser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='lkoordinat_kvalitet_nr',
        ),
        migrations.AddField(
            model_name='building',
            name='lkoordinat_kvalitet_kode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Coordinate Quality Number'),
        ),
        migrations.AlterField(
            model_name='building',
            name='bygningsstatus_nr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Building Status Number'),
        ),
    ]
