# Generated by Django 4.0.4 on 2022-08-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_remove_building_lkoordinat_kvalitet_nr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='antall_boliger',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Number of Apartments'),
        ),
        migrations.AlterField(
            model_name='building',
            name='antall_etasjer',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Number of Floors'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Building ID'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Building Number'),
        ),
        migrations.AlterField(
            model_name='building',
            name='bygning_lnr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Building LNR'),
        ),
        migrations.AlterField(
            model_name='building',
            name='bygningstype_nr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Building Type Number'),
        ),
        migrations.AlterField(
            model_name='building',
            name='city_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='building',
            name='county_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='County Number'),
        ),
        migrations.AlterField(
            model_name='building',
            name='eiendom_antall',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Number of Properties'),
        ),
        migrations.AlterField(
            model_name='building',
            name='godkjent_dato',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Approved Date'),
        ),
        migrations.AlterField(
            model_name='building',
            name='igangsatt_dato',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='building',
            name='lkoordinatsystem_nr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Coordinate System Number'),
        ),
        migrations.AlterField(
            model_name='building',
            name='tatt_i_bruk_dato',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='In Use Date'),
        ),
        migrations.AlterField(
            model_name='building',
            name='vannforsyning_nr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Water Supply Number'),
        ),
    ]
