# Generated by Django 4.0.4 on 2022-10-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0012_alter_building_antall_boliger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Building Number')),
                ('city_number', models.IntegerField(blank=True, null=True, verbose_name='City Name')),
                ('city_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='City Name')),
                ('bygning_lnr', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Building LNR')),
                ('bygningstype_nr', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Building Type Number')),
                ('bygningstype_navn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Building Type Name')),
                ('bygningsstatus_nr', models.CharField(blank=True, max_length=10, null=True, verbose_name='Building Status Number')),
                ('bygningsstatus_navn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Building Status Name')),
                ('godkjent_dato', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Approved Date')),
                ('igangsatt_dato', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Start Date')),
                ('tatt_i_bruk_dato', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='In Use Date')),
                ('bruksareal_totalt', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='UFS Total')),
                ('kommune_nr_adr', models.IntegerField(blank=True, null=True, verbose_name='Kommune Nr Adr')),
                ('kommune_navn_adr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kommune Navn Adr')),
                ('adresse_id', models.IntegerField(blank=True, null=True, verbose_name='Address ID')),
                ('gatenavn', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gate Name')),
                ('gatenavnkode', models.IntegerField(blank=True, null=True, verbose_name='Gate Number')),
                ('husnummer', models.IntegerField(blank=True, null=True, verbose_name='Number of Houses')),
                ('bokstav', models.CharField(blank=True, max_length=5, null=True, verbose_name='Letter')),
                ('undernummer', models.IntegerField(blank=True, null=True, verbose_name='Number of Subunits')),
                ('post_nr', models.IntegerField(blank=True, null=True, verbose_name='Postal Code')),
                ('poststed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Postal Location')),
            ],
        ),
    ]
